### ISSUE TITLE
empty list of tasks in the monitor

### ISSUE THREAD

**Issue by madisvain** [jezdez/django-celery-monitor#41]
Why might the list of tasaks be empty? When I look at the log with tail I can see tasks beeing processed. But somehow these are not showing up for the monitor.

![screenshot 2017-12-09 21 10 52](https://user-images.githubusercontent.com/727994/33798682-ab0dbd52-dd25-11e7-95cb-ef9e4e77c6d7.png)

**Comment by jezdez** [comment]
@madisvain I think you're confusing the [Celery Curses monitor](http://docs.celeryproject.org/en/latest/userguide/monitoring.html#celery-events-curses-monitor) with the Django admin based monitor that django-celery-monitor provides. Here's a screenshot:

![screen-shot-2018-01-03-17-18-59](https://user-images.githubusercontent.com/1610/34528829-6737d8ae-f0aa-11e7-851b-cdca5b8e4379.png)

**Comment by UmeshDe** [comment]
I have the same issue. not resolved after celery -A proj worker -l info -E also ..
While running this celery -A utility events -l info --camera django_celery_monitor.camera.Camera --frequency=5.0

[2020-06-24 15:16:15,752: ERROR/MainProcess] Error in timer: TypeError('get() argument after ** must be a mapping, not str',)
Traceback (most recent call last):
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 169, in apply_entry
    entry()
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 130, in _reschedules
    return fun(*args, **kwargs)
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/celery/events/snapshot.py", line 72, in capture
    self.state.freeze_while(self.shutter, clear_after=self.clear_after)
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/celery/events/state.py", line 464, in freeze_while
    return fun(*args, **kwargs)
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/celery/events/snapshot.py", line 69, in shutter
    self.on_shutter(self.state)
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/django_celery_monitor/camera.py", line 125, in on_shutter
    self.handle_worker(worker)
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/django_celery_monitor/camera.py", line 77, in handle_worker
    update_freq=self.worker_update_freq,
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/django_celery_monitor/managers.py", line 65, in update_heartbeat
    defaults={'last_heartbeat': heartbeat},
  File "/media/pc/new/projects/utilityapp/env/lib/python3.6/site-packages/django_celery_monitor/managers.py", line 36, in select_for_update_or_create
    obj = self.select_for_update().get(**lookup)
TypeError: get() argument after ** must be a mapping, not str


this error!
